### ISSUE TITLE
Replace Image that has a Thumbnail

### ISSUE THREAD

**Issue by href** [amol-/depot#32]
I'm using the thumbnail filter to generate thumbnails for images and I've noticed that when i replace an existing image, the thumbnail file-id changes, even though the image file-id stays the same.

I had a look at the thumbnail filter and it seems to me that it would be easy to modify it so that it would replace the thumbnail instead of creating a new one. If not for the builtin filter, I would at least like to do that for my own, to be able to permanently redirect to thumbnails.

The only problem is that there's currently no way to access the old file in a filter. However, the value is still present higher up in the stack.

How would you feel about passing down that value to `_apply_filters` [from the `_field_set` method in sqlalchemy.py](https://github.com/amol-/depot/blob/6f3587e/depot/fields/sqlalchemy.py#L75)?

It wouldn't be backwards compatible with existing filters unless we inspect their signature, but apart from that I see no drawbacks. If you think this would make a good addition I'm happy to provide a PR.

**Comment by amol-** [comment]
If by replacing the old thumbnail you mean to physically replace the existing file, that is something you can't do. Doing so will break the unit of work and transaction support in DEPOT.

DEPOT is only able to rollback file changes when the transaction is rolled back exactly because it never replaces anything and only creates new entities. So when you rollback the transaction you just delete the new file and keep the old one, while when committing the transaction you keep the new one and delete the old old.

**Comment by href** [comment]
Oh I see. I got a bit confused with the id of my database record (nothing to do with depot), the internal file id and the replace function. I kind of thought the replace function would physically replace the file, but I now see that it deletes the old and promotes a new one. And since I have my own file id I don't have to worry about this anyway :)

Thanks!
